apiVersion: skaffold/v1
kind: Config
build:    # build部分与deploy部分是独立的，可以随意组合
  artifacts:
    - image: docker.hirisun.com/demo-springboot #registry.hub.docker.com/zhouxb009/dev
      jib:
        args:
          #- -DsendCredentialsOverHttp=true
          - -DskipTests
        type: maven
  insecureRegistries:
    - docker.hirisun.com
  tagPolicy:
    #sha256: {}
    dateTime:   #image tag, 标准时间格式：2006-01-02_15-04-05.999_MST
      format: 2006-01-02-15-04
      timezone: Local
  local:
    push: true
deploy:
  kubectl:
    manifests:
      - app.yaml
      - istio.yaml
    flags:
      apply:
        - --force=true
        - --grace-period=0